CFLAGS = -mcpu=cortex-m4 -mthumb -nostdlib -Iinclude

all: firmware.elf

firmware.elf: platform/startup.s examples/button-input-blinky/main.c
	arm-none-eabi-gcc $(CFLAGS) -T platform/stm32f446.ld platform/startup.s examples/button-input-blinky/main.c -o firmware.elf

clean:
	rm -f firmware.elf

flash:
	openocd -f interface/stlink.cfg -f target/stm32f4x.cfg -c "program firmware.elf verify reset exit"